function str = getCbuilder(object)

%   getCbuilder Generates a string of C code for the computation 
%                 of model vector field 
%
    str = sprintf('RE_model(%e,%e,%e,%e,%e,%e,%e,%e,%e,%e,%e,%e,%e,%e,%e,%e,%e,%e,%e,%e,%e)',...
    object.gna,object.ENa,object.gk,object.Ek,object.gca,object.gl,...
    object.El,object.C,object.Iapp,object.Ca0,object.d,...
    object.KT,object.Kd,object.gd,object.D,object.EsynEx,object.tau,...
    object.tTm1,object.tTm2,object.tTh1,object.tTh2);
end